server:  
   port: 8500  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: password
    url: jdbc:mysql://layoverconnect-db.cxl4dqhvo99b.ap-south-1.rds.amazonaws.com:3306/db_layover_connect?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
     multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 5MB    
 
  mail:  
    host: smtp.gmail.com
    username: layoverconnect123@gmail.com
    password: rnlqhmhzjpjxuvaf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    csrf:
      enabled: true
logging:  
     file:
       url : /home/ec2-user/Client_Layoverconnect_Backend_JavaSpringBoot/layover-connect/src/main/resources/layover-connect-logs/layover.log    
auth.app:
    jwt-secret: qwerty
    jwt-expiration-ms: 86400000 #24*60*60*1000
    jwt-refresh-ms: 1296000000  #15*24*60*60*1000
    jwt-not-before-ms: 3000     #3*1000 